### ISSUE TITLE
limited API for cross-site contests page

### ISSUE THREAD

**Issue by nyiyui** [mcpt/ctf#10]
Add a limited API to for an "all contests" page for MCPT.

- `/api/v1/contests` returns a list of public contests with their title, description, timeframes, and type (i.e. team or individual)

**Comment by JasonLovesDoggo** [comment]
What's the use case for this exactly?

**Comment by nyiyui** [comment]
I was thinking that there could be some way to show announcements/contests
for both competitive and cybersecurity.

**Comment by JasonLovesDoggo** [comment]
Ahhhhh Okay (Low priority tho lol)

**Comment by JasonLovesDoggo** [comment]
Easy to do now that ninja was added - will do it soon
